eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOSTNAME:localhost}:9411/api/v2/spans

security:
  oauth2:
    client:
      registration:
        okta:
          client-id: ${OKTA_CLIENT_ID}
          client-secret: ${OKTA_CLIENT_SECRET}
          scope: openid, profile, email, offline_access
      provider:
        okta:
          issuer-uri: https://integrator-3283424.okta.com/oauth2/default
    resourceserver:
      jwt:
        issuer-uri: https://integrator-3283424.okta.com/oauth2/default
