eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOSTNAME:localhost}:9411/api/v2/spans

spring: 
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid, profile, email, offline_access
        provider:
          auth0:
            issuer-uri: https://dev-bdj1h0lwbhif83d1.us.auth0.com/
        resourceserver:
          jwt:
            issuer-uri: https://dev-bdj1h0lwbhif83d1.us.auth0.com/

# OKTA CONFIGURATION (commented out - kept for reference)
#security:
#  oauth2:
#    client:
#      registration:
#        okta:
#          client-id: ${OKTA_CLIENT_ID}
#          client-secret: ${OKTA_CLIENT_SECRET}
#          scope: openid, profile, email, offline_access
#      provider:
#        okta:
#          issuer-uri: https://integrator-3283424.okta.com/oauth2/default
#      resourceserver:
#        jwt:
#          issuer-uri: https://integrator-3283424.okta.com/oauth2/default
