server:
  port: 8088

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/smartaera/config-server
          clone-on-start: true
          default-label: main

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-0.eureka:8761/eureka
